sudo: false
language: node_js
notifications:
  email: false
node_js:
  - "10"
before_install:
  - npm i -g npm@^6.0.0
before_script:
  - npm prune
script:
  - npm run test
deploy:
  provider: npm
  api_key: $NPM_TOKEN
